version: "3.8"
services:
  webserver:
    build:
      context: .
    ports:
      - "9000:9000"
      - "80:80"
    volumes:
      - ./wait.sh:/scripts/wait.sh
  db:
    image: mysql:5.7.32
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:6.7.2
    ports:
      - "9200:9200"
    environment:
      - cluster.name=magento2_justright
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  database:
